# Generated by Django 3.1.7 on 2023-10-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0003_auto_20230817_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafileupload',
            old_name='file_name',
            new_name='cc_num',
        ),
        migrations.RemoveField(
            model_name='datafileupload',
            name='description',
        ),
        migrations.RemoveField(
            model_name='datafileupload',
            name='trained_model_data',
        ),
        migrations.RemoveField(
            model_name='datafileupload',
            name='x_test_data',
        ),
        migrations.RemoveField(
            model_name='datafileupload',
            name='y_test_data',
        ),
        migrations.AddField(
            model_name='datafileupload',
            name='status',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
