# Generated by Django 3.1.7 on 2023-10-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0004_auto_20231028_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_num', models.CharField(default=0, max_length=50)),
                ('actual_file', models.FileField(upload_to='uploads/')),
                ('status', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DataFileUpload',
        ),
    ]
